# Generated by Django 6.1.1 on 2026-09-18 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_group_profile_picture_alter_groupmembership_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('text', 'Text'), ('link', 'Link'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True, max_length=5000)),
                ('link_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='groups.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
