# Generated by Django 6.1.1 on 2026-09-15 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('category', models.CharField(choices=[('demonstration', 'Demonstration'), ('march', 'March'), ('rally', 'Rally'), ('town_hall', 'Town Hall'), ('community_meeting', 'Community Meeting'), ('canvassing', 'Political Canvassing'), ('neighborhood_organizing', 'Neighborhood Organizing'), ('environmental_cleanup', 'Environmental Cleanup'), ('fundraiser', 'Fundraiser'), ('public_forum', 'Public Forum'), ('vigil', 'Peaceful Vigil'), ('other', 'Other')], max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('general_area', models.CharField(blank=True, help_text="e.g. 'Downtown Park' or 'Near City Hall' - shown publicly before RSVP", max_length=255)),
                ('exact_address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public - anyone can see and RSVP'), ('unlisted', 'Unlisted - only accessible via direct link'), ('private', 'Private - invite only')], default='public', max_length=10)),
                ('address_visible_to_all', models.BooleanField(default=False, help_text='If False, exact_address only shown to confirmed RSVPs')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
