# Generated by Django 6.1.1 on 2026-09-18 22:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eyebrow', models.CharField(blank=True, help_text="Small label above the headline, e.g. 'GET INTO IT'", max_length=100)),
                ('headline', models.CharField(max_length=200)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='banners/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active banner is shown at a time, on the events page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
