# Generated by Django 6.1.1 on 2026-09-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_herobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='headline',
            field=models.CharField(blank=True, help_text='Leave blank to show the photo on its own, with no text overlay (e.g. if the photo already has messaging baked in)', max_length=200),
        ),
    ]
