# Generated by Django 6.1.1 on 2026-09-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_is_draft_savedevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('going', 'Going'), ('pending', 'Pending Approval'), ('interested', 'Interested'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='going', max_length=15),
        ),
    ]
