# Generated by Django 6.1.1 on 2026-09-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_profile_picture_alter_groupmembership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='posts_visible_to_non_members',
            field=models.BooleanField(default=True, help_text="If True, anyone can view posts even without joining. Only applies to private groups (public groups' posts are always visible)."),
        ),
    ]
