# Generated by Django 6.1.1 on 2026-09-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_posts_visible_to_non_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member_list_public',
            field=models.BooleanField(default=False, help_text="If True, non-members can view the group's member list."),
        ),
    ]
