# Generated by Django 6.1.1 on 2026-09-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_member_list_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/banners/'),
        ),
    ]
