# Generated by Django 6.1.1 on 2026-09-19 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('event_reminder', 'Event reminder'), ('post_comment', 'New comment'), ('post_likes', 'Likes milestone'), ('group_accepted', 'Group membership accepted'), ('event_accepted', 'Event RSVP accepted')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
